version: '3'
services:

  cache:
    image: redis:3.2.10
    expose:
      - "6379"
    ports:
      - "6379:6379"

  fulltextsearch_db:
    image: postgres:9.6
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
